/* eslint-disable prettier/prettier */
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        backgroundColor: '#fff',
        flex: 1,
    },
    avatarSetting: {
        justifyContent: 'center',
        alignItems: 'center',
        top: 20,
    },
    avatar: {
        width: 150,
        height: 150,
        borderRadius: 100,
    },
    avJustify: {
        backgroundColor: '#f2f2f2',
        width: 157,
        height: 157,
        borderColor: '#9038A5',
        borderWidth: 2,
        borderRadius: 100,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#9038a5',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.9,
        shadowRadius: 3.5,
        elevation: 7,
    },
    userNameSetting: {
        justifyContent: 'center',
        alignItems: 'center',
        top: 30,
    },
    userNametxt: {
        fontSize: 30,
        fontWeight: 'bold',
        color: '#000',
        textAlign: 'center',
    },
    uploadImgBtnSetting: {
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        top: 60,
        backgroundColor: '#9038A5',
        padding: 12,
        borderRadius: 5,
        width: 140,
    },
    uploadImgTxt: {
        color: '#fff',
        fontSize: 15,
        fontWeight: 'bold',
    },
    infoSetting: {
        backgroundColor: '#9038A5',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        padding: 12,
        borderRadius: 5,
        width: 140,
        top: 65,
    },
    infoTxt: {
        color: '#fff',
        fontSize: 15,
        fontWeight: 'bold',
    },
    infoModalBgSetting: {
        backgroundColor: '#00000999',
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    infoModalFrontSetting: {
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 15,
        width: '90%',
    },
    infoModalTxt: {
        color: '#000',
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        margin: 10,
        bottom: 10,
        lineHeight: 30,
    },
    infoModalCloseTxt: {
        backgroundColor: '#9038A5',
        padding: 10,
        color: '#fff',
        borderRadius: 6,
        width: '96.5%',
        textAlign: 'center',
        margin: 10,
        left: -3,
    },
    generalInfoSetting: {
        backgroundColor: '#f3f3f3',
        justifyContent: 'center',
        width: '90%',
        top: 110,
        padding: 7,
        left: '5%',
        borderRadius: 5,
    },
    generalInfotxt: {
        color: '#2874a6',
        fontSize: 15,
        left: '3%',
    },
    removeAccSetting: {
        backgroundColor: '#f3f3f3',
        justifyContent: 'center',
        width: '90%',
        top: 170,
        padding: 7,
        left: '5%',
        borderRadius: 5,
    },
    removeAccTxt: {
        color: '#cb4335',
        fontSize: 15,
        left: '3%',
    },
    removeAcc: {
        backgroundColor: '#cb4335',
        padding: 10,
        color: '#fff',
        borderRadius: 6,
        width: '96.5%',
        textAlign: 'center',
        margin: 10,
        left: -3,
    },
    avatarBtn: {
        backgroundColor: '#f3f3f3',
        justifyContent: 'center',
        width: '90%',
        top: 90,
        padding: 7,
        left: '5%',
        borderRadius: 5,
    },
    avatarBtnTxt: {
        color: '#1e8449',
        fontSize: 15,
        left: '3%',
    },
    logoutSetting: {
        backgroundColor: '#f3f3f3',
        justifyContent: 'center',
        width: '90%',
        top: 190,
        padding: 7,
        left: '5%',
        borderRadius: 5,
    },
    logoutTxt: {
        color: '#938',
        fontSize: 15,
        textAlign: 'center',
    },
    yourInfoTxt: {
        color: '#000',
        backgroundColor: '#f2f2f2',
        borderColor: '#9038A5',
        borderWidth: 0.6,
        borderRadius: 4,
        padding: '3%',
        margin: 5,
    },
    changeInfoSetting: {
        backgroundColor: '#f3f3f3',
        justifyContent: 'center',
        width: '90%',
        top: 150,
        padding: 7,
        left: '5%',
        borderRadius: 5,
    },
    changeInfoTxt: {
        color: '#d35400',
        fontSize: 15,
        left: '3%',
    },
    updateBtnTxt: {
        backgroundColor: '#229954',
        padding: 10,
        color: '#fff',
        borderRadius: 6,
        width: '96.5%',
        textAlign: 'center',
        margin: 10,
        left: -3,
    },
    updateInfoTxt: {
         left: '1%',
         fontSize: 15,
         color: '#000',
         margin: 2,
         fontWeight: 'bold',
    },
    addMoreInfoSetting: {
        backgroundColor: '#f3f3f3',
        justifyContent: 'center',
        width: '90%',
        top: 130,
        padding: 7,
        left: '5%',
        borderRadius: 5,
    },
    addMoreInfotxt: {
        color: '#9c640c',
        fontSize: 15,
        left: '3%',
    },
    eyeBtnSetting: {
        top: '-9%',
        right: '5%',
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
        alignSelf: 'flex-end',
    },
});

export { styles };