/* eslint-disable prettier/prettier */
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        backgroundColor: '#fff',
        flex: 1,
    },
    headerSetting: {
        backgroundColor: '#9038A5',
        padding: 30,
        borderBottomLeftRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTxt: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
    },
    scrollSetting: {
        //flexDirection: 'row',
        top: 30,
    },
    humanDiseaseSetting: {
        backgroundColor: '#f2f2f2',
        width: 350,
        height: 550,
        //top: 5,
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.3,
        shadowRadius: 3.5,
        elevation: 5,
        margin: 10,
    },
    humanDisease: {
        backgroundColor: '#9038A5',
        padding: 10,
        top: 81,
        height: 300,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        borderTopLeftRadius: 300,
        justifyContent: 'center',
        alignItems: 'center',
    },
    humanImgSetting: {
        justifyContent: 'center',
        alignItems: 'center',
        top: 30,
    },
    humanImg: {
        backgroundColor: '#fff',
        borderRadius: 100,
        width: 170,
        height: 170,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.3,
        shadowRadius: 3.5,
        elevation: 10,
    },
    img: {
        width: 165,
        height: 165,
        borderRadius: 100,
    },
    humanTxt: {
        color: '#fff',
        fontSize: 32,
        fontWeight: 'bold',
        left: 20,
        top: 40,
        //flexWrap: 'wrap',
        textAlign: 'center',
        lineHeight: 43,
    },
    backDesign: {
        backgroundColor: '#9038A5',
        width: 270,
        height: 300,
        opacity: 0.03,
        borderRadius: 100,
        transform: [{ rotate: '40deg' }],
        zIndex: -1,
        top: 300,
    },
    searchSetting: {
        backgroundColor: '#f9f9f9',
        borderRadius: 7,
        borderColor: '#9038a5',
        borderWidth: 0.6,
        width: '90%',
        height: 40,
        justifyContent: 'center',
        alignSelf: 'center',
        marginTop: 50,
    },
    searchInput: {
        color: '#839192',
        left: 12,
        top: 1.5,
    },
});

export { styles };
